# Generated by Django 5.2.12 on 2026-03-14 18:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notification_is_read'),
        ('orders', '0002_order_orders_orde_user_id_0ae59f_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='notification',
            constraint=models.UniqueConstraint(fields=('order', 'notification_type'), name='unique_order_notification'),
        ),
    ]
